version: '3.4'

services:
  ndtnfhomework003ioc:
    image: ndtnfhomework003ioc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
